// <auto-generated />
using System;
using AirlineAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220416171936_classchanges")]
    partial class classchanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AirlineLibrary.Models.Flightsmaster", b =>
                {
                    b.Property<int>("FlightregistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightregistrationId"), 1L, 1);

                    b.Property<decimal?>("Businessseats")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Economyseats")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Flightname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightregistrationId");

                    b.ToTable("FlightMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
